name: applying
on:  

  workfow_dispatch:
    inputs:
      action:
        discription: "working on newrelic"
        require: true
        default: "apply"
        options: 
          - 'apply'
          - 'destroy'

jobs:
  job1:
    runs-on : ubuntu-latest
    steps:
      - name: "Setup - Checkout"
        uses: actions/checkout@v2.1.0
      - name: "Setup - Terraform CLI"
        uses: hashicorp/setup-terraform@v1
      # - name: Terraform Monitoring
      #   uses: maathor/terraform-new-relic-event-action@master
        with:
         NEW_RELIC_API_KEY: ${{ secrets.NEW_RELIC_API_KEY }}
         NEW_RELIC_ACCOUNT_ID: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}

      - name: terraform init
        run: |
          cd alert
          terraform init
      - name: terraform plan
        run: |
          cd alert
          terraform plan
      - name: terraform apply
          run: |
            cd alert
            terraform ${{github.event.inputs.action}} -auto-approve
      # - name: terraform destroy
        
      #     run: |
      #       cd alert
      #       terraform destroy -auto-approve

