      # - name: Terraform Monitoring
      #   uses: maathor/terraform-new-relic-event-action@master
name: applying

on:  

  workflow_dispatch:
    inputs:
      action:
        description: 'Apply or Destroy'
        required: true
        default: 'apply'
        options:
          - 'apply'
          - 'destroy'

      value:
        description: "creating workflow"
        required: true
        option:
        - 'apply'
        - 'destroy'

jobs:
  job-make-infra:
    runs-on : ubuntu-latest

    steps:
      - name: "Setup - Checkout"
        uses: actions/checkout@v2.1.0

      - name: "Setup - Terraform CLI"
        uses: hashicorp/setup-terraform@v1
        # with:

        #  api_key: ${{ secrets.NEW_RELIC_API_KEY }}

        #  account_id: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}

 

      - name: terraform init
        run: |
          cd dashboard
          terraform init
      - name: terraform plan
        run: |
          cd dashboard
          terraform plan

      - name: terraform ${{github.event.inputs.value}}
        # if: github.event.inputs.action == 'apply'
        run: |
          cd dashboard
          terraform ${{github.event.inputs.action}} -auto-approve